printing picture out
moov-io/authn pull request #30
Opened 2020-09-21 17:21 UTC by jmbrown412

In an effort to troubleshoot if the `Picture` field is being truncated before it gets back to authn, this PR prints out the field to check it's value.

2020-09-21 17:24 UTC, InfernoJJ requested changes

2020-09-21 17:24 UTC, InfernoJJ commented on pkg/providers/openid/controller_generic_oidc.go
> +			fmt.Printf("picture=%q\n", claims.Picture)
Use logging so its searchable. You won't be able to see a println like that.

2020-09-21 20:57 UTC, InfernoJJ approved these changes

2020-09-21 21:00 UTC, merged

2020-09-22 19:41 UTC, adamdecaf commented
@jmbrown412 @InfernoJJ do we have plans to revert this now that we've identified the problem?

2020-09-22 20:39 UTC, InfernoJJ commented
I'd revert it once its we fixed the image url.